### ISSUE TITLE
Public databases are no longer available

### ISSUE THREAD

**Issue by maxwellb** [orientechnologies/public-databases#4]
The links to the ZIP files on orientdb.com are broken. Please provide updated links and/or consider add as releases in GitHub.

**Comment by luigidellaquila** [comment]
Hi @maxwellb 

The public databases are still there, please try this: https://www.orientdb.com/public-databases/3.0.x/config.json

Thanks

Luigi

**Comment by luigidellaquila** [comment]
I just noticed that the links in this repo were wrong, I updated them

Thanks

Luigi

**Comment by maxwellb** [comment]
Looks good to me. Thank you!
